### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/evaluacion-intermedia-modulo-2-sandra9ro#1]
Muy buen trabajo @sandra9ro  !!!

- [ ] Solo te pido una mejora y es que los elmentos HTML de las pistas y del contador sean párrafos (y no inputs).

Te ha quedado un código muy limpio!!!

**Comment by sandra9ro** [comment]
La verdad es que sí me gustaría que me lo corrigieras. Lo tengo ya terminado, hago un merge con la master
